# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 송지훈
title: 시스템 엔지니어
email: sjh9646@naver.com
# email_title: Email (Email title override)
phone: 010-9130-0723
# phone_title: Phone (Phone title override)
# website: https://velog.io/@jihoon_song
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  ssongJiHun

# Additional icon links
additional_links:
- title: blog
  icon: fa fa-blog
  url: https://velog.io/@jihoon_song
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  

content:


  - title: Experience
    layout: list
    content:
      - layout: left
        title: (주)소더코드
        link: https://www.sothecode.com/
        sub_title: 시스템 엔지니어링
        caption: 2022.07 ~ 현재
        
        quote: >
          소더코드 주력 서비스
        description: | # this will include new lines to allow paragraphs
          - MQTTCLIENT, PUB/SUB 사용 개편 (AWS-MQTTCLIENT 이용)
          - ERP 시스템 서비스 풀스택 개발 (REACT / NodeJs-Express)
          - AWS EC2 서비스 배포 및 로드벨런싱 작업





  - title: 역량
    layout: list
    content:
      - layout: top-middle
        title: 모바일 게임 엔지니어링
        caption: 2013.03 ~ 2014.07
        description: | # this will include new lines to allow paragraphs
          - 캐주얼 게임 "버블버블" 하이브리드 모바일 게임 개발 및 배포 (Cocos2d-x 엔진 사용 C++)
          - 캐주얼 게임 "탭브릭" 하이브리드 모바일 게임 개발 및 배포 (Cocos2d-x 엔진 사용 C++)
          - "탭브릭" 안정화를 위한 Unity2D엔진(C#) 사용
          - 랭킹시스템을 위한 구글플레이 및 카카오 SDK 연동
      - layout: top-middle
        title: 모바일 엔지니어링
        description: | # this will include new lines to allow paragraphs
          - 전국 학교 급식 애플리케이션 "삼시세끼" 개발 및 배포 for Android
          - "삼시세끼" 실시간 알람 시스템 구축
          - 메모 애플리케이션 개발 및 배포 for Android
          - 코드미터 하이브리드 웹앱 개발 (Android / IOS)
          - 코드미터 Firebase Massaging(FCM)을 사용해 실시간 알람 시스템 개발
  
      - layout: top-middle
        title: 웹 엔지니어링
        description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: 데이터 처리 및 개선
        description: | # this will include new lines to allow paragraphs
          - "삼시세끼" 교육청 OPENAPI 사용, 데이터 후처리
          - ERP 데이터베이스 API 개발 및 운영 (NodeJS)
          - ERP JWT를 이용, AccessToken, refreshToken을 사용, 계정 보안 강화 (NodeJS)
          - 랭킹 시스템 시스템 API 개발 및 운영 (PHP)
          - 네이버 지도 API, Geolocatrion API을 이용한 현재 위치 및 주변 맛집 탐색
          
      - layout: top-middle
        title: 견고한 데이터 구조 및 애플리케이션 설계
        description: | # this will include new lines to allow paragraphs
          - ERP 데이터 베이스 인덱스 트리 구성
          - 랭킹시스템을 위한 계정 테이블과 랭킹테이블 구성
          - JSON데이터 저장을 위한 NoSql 구성



  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Cocos2d-x (C++)을 사용한 하이브리드 모바일 게임
          - Android(Google Play), IOS(App Store)  
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Cocos2d-x (C++)을 사용한 하이브리드 모바일 게임
          - Android(Google Play), IOS(App Store)  
      - layout: Frontend
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Cocos2d-x (C++)을 사용한 하이브리드 모바일 게임
          - Android(Google Play), IOS(App Store)  





  - title: Opensource
    layout: list
    content:
      - layout: left
        title: 개인블로그
        link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs






  - title: Education
    layout: list
    content:
      - layout: left
        title: GIT 교과서
        description: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
