name: "NOTION COMMIT AND DEPLOY"
on:
  repository_dispatch:
    types: [RUN_REPOSITORY_DISPATCH_NOTION]

jobs:
  setting:

    runs-on: ubuntu-latest

    steps:
      # 레포지토리의 코드를 사용
      - uses: actions/checkout@v4

      # 환경을 Node.js로 설정
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      # node_modules가 변화가 있을 때만 사용하기 위해 캐쉬 액션
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      # node_modules의 변화가 있을 때만 npm install
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      # notion blog database 접근 md 파일 생성
      - name : 'notion database access'
        run: node _action/notion-import.js
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          NOTION_BLOG_DB_ID: ${{secrets.NOTION_BLOG_DB_ID}}

      # 빌드 및 commit

      # 생성된 파일 commit
      - name: Add date and push
        run: |
          git add .
          git config --global user.email "ssongJiHuns@github.com"
          git config --global user.name "ssongJiHun"
          git commit -am "auto_blog_update"
          git push origin blogs-develop

      # - name : 'deploy'
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
