name: "Build and Deploy"
on:
  repository_dispatch:
    types: [RUN_WORKFLOW_DISPATCH]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name : 'generate Environment Varialbes'
        run: node _scripts/notion-import.js
        env:
          NOTION_TOKEN: ${{secrets.DATABASE_NAME}}
          DATABASE_ID: ${{secrets.NOTION_TOKEN}}
