name: "Build and Deploy"
on:
  repository_dispatch:
    types: [RUN_WORKFLOW_DISPATCH]

jobs:
  setting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name : 'generate Environment Varialbes'
        run: node _scripts/notion-import.js
        env:
          NOTION_TOKEN: ${{secrets.DATABASE_NAME}}
          DATABASE_ID: ${{secrets.NOTION_TOKEN}}
