name: "Build and Deploy"
on:
  repository_dispatch:
    types: [RUN_WORKFLOW_DISPATCH]

jobs:
  setting:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name : 'env echo'
        run : 'echo "$NOTION_TOKEN" | base64'
        shell: bash
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}

      - name : 'generate Environment Varialbes'
        run: node _scripts/notion-import.js
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          DATABASE_ID: ${{secrets.DATABASE_NAME}}
